// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Source.Models;

#nullable disable

namespace Source.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724065854_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Source.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các loại bánh burger thơm ngon",
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pizza nóng hổi, nhiều phô mai",
                            Name = "Pizzas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gà chiên giòn rụm",
                            Name = "Gà Rán"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nước ngọt, khoai tây chiên, kem",
                            Name = "Thức uống & Tráng miệng"
                        });
                });

            modelBuilder.Entity("Source.Models.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "2 Burger Bò Phô Mai + 1 Khoai Tây Chiên + 2 Coca Cola. Tiết kiệm hơn!",
                            ImageUrl = "/images/combo_family.svg",
                            Name = "Combo Gia Đình",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "1 Pizza Hải Sản + 1 Gà Rán Giòn Cay + 1 Khoai Tây Chiên + 2 Coca Cola. Cực vui cực đã!",
                            ImageUrl = "/images/combo_party.svg",
                            Name = "Combo Tiệc Tùng",
                            Price = 200000m
                        });
                });

            modelBuilder.Entity("Source.Models.ComboDetail", b =>
                {
                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("FastFoodId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ComboId", "FastFoodId");

                    b.HasIndex("FastFoodId");

                    b.ToTable("ComboDetails");

                    b.HasData(
                        new
                        {
                            ComboId = 1,
                            FastFoodId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            ComboId = 1,
                            FastFoodId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            ComboId = 1,
                            FastFoodId = 7,
                            Quantity = 2
                        },
                        new
                        {
                            ComboId = 2,
                            FastFoodId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            ComboId = 2,
                            FastFoodId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            ComboId = 2,
                            FastFoodId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            ComboId = 2,
                            FastFoodId = 7,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Source.Models.FastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FastFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Bánh burger kẹp thịt bò nướng thơm ngon cùng lớp phô mai béo ngậy và rau tươi.",
                            ImageUrl = "/images/burger_cheese.svg",
                            Name = "Burger Bò Phô Mai",
                            Price = 55000m,
                            Theme = "Gia đình"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Bánh burger kẹp thịt gà chiên giòn tan, sốt mayonnaise và xà lách ngon tuyệt.",
                            ImageUrl = "/images/burger_chicken.svg",
                            Name = "Burger Gà Giòn",
                            Price = 50000m,
                            Theme = "Trẻ em"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Pizza với mực, tôm, thanh cua tươi ngon cùng phô mai Mozzarella thượng hạng.",
                            ImageUrl = "/images/pizza_seafood.svg",
                            Name = "Pizza Hải Sản",
                            Price = 120000m,
                            Theme = "Tiệc tùng"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Pizza đầy ắp thịt nguội, xúc xích pepperoni, ớt chuông, nấm và phô mai.",
                            ImageUrl = "/images/pizza_mixed.svg",
                            Name = "Pizza Thập Cẩm",
                            Price = 110000m,
                            Theme = "Gia đình"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Một miếng gà rán giòn rụm, tẩm ướp gia vị cay nồng đậm đà.",
                            ImageUrl = "/images/chicken_spicy.svg",
                            Name = "Gà Rán Giòn Cay",
                            Price = 35000m,
                            Theme = "Ăn vặt"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Khoai tây chiên vàng giòn, rắc chút muối thơm ngon.",
                            ImageUrl = "/images/fries.svg",
                            Name = "Khoai Tây Chiên",
                            Price = 25000m,
                            Theme = "Ăn vặt"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Nước ngọt có ga Coca Cola mát lạnh.",
                            ImageUrl = "/images/coca.svg",
                            Name = "Coca Cola",
                            Price = 15000m,
                            Theme = "Ăn uống"
                        });
                });

            modelBuilder.Entity("Source.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrderDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Source.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<int?>("FastFoodId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("FastFoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Source.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Tô Ký, Quận 12, TP.HCM",
                            Email = "admin@fastfood.com",
                            FullName = "Quản Trị Viên",
                            PasswordHash = "$2a$11$ezY8eus712l.J/TErYvnveHybjXijpr.j7gucKR7G0q3xlgK6WCc6",
                            PhoneNumber = "0987654321",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Đường Quang Trung, Gò Vấp, TP.HCM",
                            Email = "customer@fastfood.com",
                            FullName = "Nguyễn Văn Khách",
                            PasswordHash = "$2a$11$YIt.Q8rHNv0BKrlePDKezedHKn7OjqQYdbTAS7EramaJSAVPn.R/6",
                            PhoneNumber = "0912345678",
                            Role = "Customer",
                            Username = "customer"
                        });
                });

            modelBuilder.Entity("Source.Models.ComboDetail", b =>
                {
                    b.HasOne("Source.Models.Combo", "Combo")
                        .WithMany("ComboDetails")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Source.Models.FastFood", "FastFood")
                        .WithMany("ComboDetails")
                        .HasForeignKey("FastFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("FastFood");
                });

            modelBuilder.Entity("Source.Models.FastFood", b =>
                {
                    b.HasOne("Source.Models.Category", "Category")
                        .WithMany("FastFoods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Source.Models.Order", b =>
                {
                    b.HasOne("Source.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Source.Models.OrderDetail", b =>
                {
                    b.HasOne("Source.Models.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.HasOne("Source.Models.FastFood", "FastFood")
                        .WithMany()
                        .HasForeignKey("FastFoodId");

                    b.HasOne("Source.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("FastFood");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Source.Models.Category", b =>
                {
                    b.Navigation("FastFoods");
                });

            modelBuilder.Entity("Source.Models.Combo", b =>
                {
                    b.Navigation("ComboDetails");
                });

            modelBuilder.Entity("Source.Models.FastFood", b =>
                {
                    b.Navigation("ComboDetails");
                });

            modelBuilder.Entity("Source.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
